# Generated by Django 6.0.4 on 2026-04-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarefa",
            old_name="concuilda",
            new_name="concluida",
        ),
    ]
