# Generated by Django 6.0.4 on 2026-04-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0001_initial"),
        ("tarefas", "0002_rename_concuilda_tarefa_concluida"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarefas",
                to="categorias.categoria",
            ),
        ),
    ]
