# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import livros_pb2 as livros__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in livros_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LivroServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CadastrarLivro = channel.unary_unary(
                '/livros.LivroService/CadastrarLivro',
                request_serializer=livros__pb2.LivroRequest.SerializeToString,
                response_deserializer=livros__pb2.LivroResponse.FromString,
                _registered_method=True)
        self.ListarLivros = channel.unary_unary(
                '/livros.LivroService/ListarLivros',
                request_serializer=livros__pb2.Empty.SerializeToString,
                response_deserializer=livros__pb2.ListaLivros.FromString,
                _registered_method=True)


class LivroServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CadastrarLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarLivros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LivroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CadastrarLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.CadastrarLivro,
                    request_deserializer=livros__pb2.LivroRequest.FromString,
                    response_serializer=livros__pb2.LivroResponse.SerializeToString,
            ),
            'ListarLivros': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarLivros,
                    request_deserializer=livros__pb2.Empty.FromString,
                    response_serializer=livros__pb2.ListaLivros.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'livros.LivroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('livros.LivroService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LivroService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CadastrarLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livros.LivroService/CadastrarLivro',
            livros__pb2.LivroRequest.SerializeToString,
            livros__pb2.LivroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarLivros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livros.LivroService/ListarLivros',
            livros__pb2.Empty.SerializeToString,
            livros__pb2.ListaLivros.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
