# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livros.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'livros.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clivros.proto\x12\x06livros\"?\n\x05Livro\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\r\n\x05\x61utor\x18\x03 \x01(\t\x12\x0b\n\x03\x61no\x18\x04 \x01(\x05\":\n\x0cLivroRequest\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\r\n\x05\x61utor\x18\x02 \x01(\t\x12\x0b\n\x03\x61no\x18\x03 \x01(\x05\"-\n\rLivroResponse\x12\x1c\n\x05livro\x18\x01 \x01(\x0b\x32\r.livros.Livro\",\n\x0bListaLivros\x12\x1d\n\x06livros\x18\x01 \x03(\x0b\x32\r.livros.Livro\"\x07\n\x05\x45mpty2\x81\x01\n\x0cLivroService\x12=\n\x0e\x43\x61\x64\x61strarLivro\x12\x14.livros.LivroRequest\x1a\x15.livros.LivroResponse\x12\x32\n\x0cListarLivros\x12\r.livros.Empty\x1a\x13.livros.ListaLivrosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livros_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIVRO']._serialized_start=24
  _globals['_LIVRO']._serialized_end=87
  _globals['_LIVROREQUEST']._serialized_start=89
  _globals['_LIVROREQUEST']._serialized_end=147
  _globals['_LIVRORESPONSE']._serialized_start=149
  _globals['_LIVRORESPONSE']._serialized_end=194
  _globals['_LISTALIVROS']._serialized_start=196
  _globals['_LISTALIVROS']._serialized_end=240
  _globals['_EMPTY']._serialized_start=242
  _globals['_EMPTY']._serialized_end=249
  _globals['_LIVROSERVICE']._serialized_start=252
  _globals['_LIVROSERVICE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
